# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - chainName: seismiclocal
    standard: EvmHypSynthetic
    decimals: 18
    symbol: ETH
    name: Ether
    addressOrDenom: "0xc007244B1d94e2d7525848FDb00e36F4e595aaE9"
    connections:
      - token: ethereum|sepolia|0x9eA7A8eC301C81115Cb6d4f4A909420a657378f3
  - chainName: sepolia
    standard: EvmHypNative
    decimals: 18
    symbol: ETH
    name: Ether
    addressOrDenom: "0x9eA7A8eC301C81115Cb6d4f4A909420a657378f3"
    connections:
      - token: ethereum|seismiclocal|0xc007244B1d94e2d7525848FDb00e36F4e595aaE9
options: {}
