# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  # STAGING #
  - chainName: pruvtest
    standard: EvmHypCollateralFiat
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: '0xA231111ad6755C06854ca1C8636CDdC101f05243'
    collateralAddressOrDenom: '0xeCacC484026a02022565496E088CA0581cC36373'
    connections:
      - token: ethereum|arbitrumsepolia|0xf04197995509E34d6e17c9F7Cc57fCCe8673825a
      - token: ethereum|sepolia|0xDccdE646A3dd411cCE613c36E9ed098E0622E784
    logoURI: /images/tokens/USDC/logo.svg
  - chainName: arbitrumsepolia
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: '0xf04197995509E34d6e17c9F7Cc57fCCe8673825a'
    collateralAddressOrDenom: '0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d'
    connections:
      - token: ethereum|pruvtest|0xA231111ad6755C06854ca1C8636CDdC101f05243
    logoURI: /images/tokens/USDC/logo.svg
  - chainName: sepolia
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: '0xDccdE646A3dd411cCE613c36E9ed098E0622E784'
    collateralAddressOrDenom: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238'
    connections:
      - token: ethereum|pruvtest|0xA231111ad6755C06854ca1C8636CDdC101f05243
    logoURI: /images/tokens/USDC/logo.svg
  ## USDT ##
  - chainName: pruvtest
    standard: EvmHypCollateralFiat
    decimals: 6
    symbol: USDT
    name: Tether USD
    addressOrDenom: '0xe0F0A2D91ca9a3db5635048f8b2be4A016bBa592'
    collateralAddressOrDenom: '0xc547f385c7D0A50Bb4b4889dF4d863F0abAD2885'
    connections:
      - token: ethereum|bsctestnet|0x3e6623b0A67CbFfaa4ac6C681bA90d8D1ac20C2f
    #      - token: ethereum|sepolia|0xfd999e47416E52D0E2e6EE080f4E0988B645f0da
    logoURI: /images/tokens/USDT/logo.svg
  - chainName: bsctestnet
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: USDT Token
    addressOrDenom: '0x3e6623b0A67CbFfaa4ac6C681bA90d8D1ac20C2f'
    collateralAddressOrDenom: '0x337610d27c682E347C9cD60BD4b3b107C9d34dDd'
    connections:
      - token: ethereum|pruvtest|0xe0F0A2D91ca9a3db5635048f8b2be4A016bBa592
    #      - token: ethereum|sepolia|0xfd999e47416E52D0E2e6EE080f4E0988B645f0da
    logoURI: /images/tokens/USDT/logo.svg
  #  - chainName: sepolia
  #    standard: EvmHypCollateral
  #    decimals: 6
  #    symbol: USDT
  #    name: Tether USD
  #    addressOrDenom: '0xfd999e47416E52D0E2e6EE080f4E0988B645f0da'
  #    collateralAddressOrDenom: '0xdF0C57f2649AEF8f45Ba1e696ACc21398cDC0f76'
  #    connections:
  #      - token: ethereum|pruvtest|0xe0F0A2D91ca9a3db5635048f8b2be4A016bBa592
  #      - token: ethereum|bsctestnet|0x3e6623b0A67CbFfaa4ac6C681bA90d8D1ac20C2f
  #    logoURI: /images/tokens/USDT/logo.svg
  ## USDT ##
  ## Test ERC20 Token - with USDC bridge fee ##
  - chainName: pruvtest
    standard: EvmHypCollateral
    decimals: 18
    symbol: MOCKRWA
    name: MockRWAToken
    addressOrDenom: '0x8188BFf405025BaA02b09c7524e73E3A16B15924'
    collateralAddressOrDenom: '0x4A1FDad497Ac84b657Ac4D0b23aeD440B4b1Fe44'
    connections:
      - token: ethereum|arbitrumsepolia|0x4C89e71cbcFA162AA678E73e7BF6dd3Eb475839e
      - token: ethereum|sepolia|0x61aFa69a38ec4A252897259BA6C8322120B13C30
  - chainName: arbitrumsepolia
    standard: EvmHypSynthetic
    decimals: 18
    symbol: MOCKRWA
    name: MockRWAToken
    addressOrDenom: '0x4C89e71cbcFA162AA678E73e7BF6dd3Eb475839e'
    connections:
      - token: ethereum|pruvtest|0x8188BFf405025BaA02b09c7524e73E3A16B15924
  #      - token: ethereum|sepolia|0x61aFa69a38ec4A252897259BA6C8322120B13C30
  - chainName: sepolia
    standard: EvmHypSynthetic
    decimals: 18
    symbol: MOCKRWA
    name: MockRWAToken
    addressOrDenom: '0x61aFa69a38ec4A252897259BA6C8322120B13C30'
    connections:
      - token: ethereum|pruvtest|0x8188BFf405025BaA02b09c7524e73E3A16B15924
  #      - token: ethereum|arbitrumsepolia|0x4C89e71cbcFA162AA678E73e7BF6dd3Eb475839e
  ## Test ERC20 Token - with USDC bridge fee ##

# STAGING #
options: {}
