# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - chainName: ethereum
    standard: EvmHypSynthetic
    decimals: 6
    symbol: ALEO
    name: Aleo
    addressOrDenom: '0x33fbC08bD84E61E04e51eA0F32885AA77F7D5ECa'
    connections:
      - token: ethereum|base|0x33fbC08bD84E61E04e51eA0F32885AA77F7D5ECa
      - token: aleo|aleo|hyp_warp_token_credits.aleo/aleo1qaqv2f6mn24xufa50d579s2pr75alxczcwl2g94favhj0dcj0yqqexazpp
      - token: ethereum|hyperevm|0x9562b536713aF52627679c2c559ebE54fB7c3cc9
  - chainName: base
    standard: EvmHypSynthetic
    decimals: 6
    symbol: ALEO
    name: Aleo
    addressOrDenom: '0x33fbC08bD84E61E04e51eA0F32885AA77F7D5ECa'
    connections:
      - token: ethereum|ethereum|0x33fbC08bD84E61E04e51eA0F32885AA77F7D5ECa
      - token: aleo|aleo|hyp_warp_token_credits.aleo/aleo1qaqv2f6mn24xufa50d579s2pr75alxczcwl2g94favhj0dcj0yqqexazpp
      - token: ethereum|hyperevm|0x9562b536713aF52627679c2c559ebE54fB7c3cc9
  - chainName: aleo
    standard: AleoHypNative
    decimals: 6
    symbol: ALEO
    name: Aleo
    addressOrDenom: hyp_warp_token_credits.aleo/aleo1qaqv2f6mn24xufa50d579s2pr75alxczcwl2g94favhj0dcj0yqqexazpp
    connections:
      - token: ethereum|ethereum|0x33fbC08bD84E61E04e51eA0F32885AA77F7D5ECa
      - token: ethereum|base|0x33fbC08bD84E61E04e51eA0F32885AA77F7D5ECa
      - token: ethereum|hyperevm|0x9562b536713aF52627679c2c559ebE54fB7c3cc9
  - chainName: hyperevm
    standard: EvmHypSynthetic
    decimals: 6
    symbol: ALEO
    name: Aleo
    addressOrDenom: '0x9562b536713aF52627679c2c559ebE54fB7c3cc9'
    connections:
      - token: ethereum|ethereum|0x33fbC08bD84E61E04e51eA0F32885AA77F7D5ECa
      - token: ethereum|base|0x33fbC08bD84E61E04e51eA0F32885AA77F7D5ECa
      - token: aleo|aleo|hyp_warp_token_credits.aleo/aleo1qaqv2f6mn24xufa50d579s2pr75alxczcwl2g94favhj0dcj0yqqexazpp
options: {}
