# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens: 
  - addressOrDenom: "0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2"
    chainName: optimism
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    connections:
      - token: ethereum|base|0x2552516453368e42705D791F674b312b8b87CD9e
      - token: ethereum|blast|0x486b39378f99f073A3043C6Aabe8666876A8F3C5
      - token: ethereum|bsc|0xE00C6185a5c19219F1FFeD213b4406a254968c26
      - token: ethereum|mode|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|linea|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|ethereum|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|fraxtal|0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5
      - token: ethereum|taiko|0x4b6aB5F819A515382B0dEB6935D793817bB4af28
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20
    symbol: ezETH
  - addressOrDenom: "0x2552516453368e42705D791F674b312b8b87CD9e"
    chainName: base
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    connections:
      - token: ethereum|optimism|0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2
      - token: ethereum|blast|0x486b39378f99f073A3043C6Aabe8666876A8F3C5
      - token: ethereum|bsc|0xE00C6185a5c19219F1FFeD213b4406a254968c26
      - token: ethereum|mode|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|linea|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|ethereum|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|fraxtal|0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5
      - token: ethereum|taiko|0x4b6aB5F819A515382B0dEB6935D793817bB4af28
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20
    symbol: ezETH
  - addressOrDenom: "0x486b39378f99f073A3043C6Aabe8666876A8F3C5"
    chainName: blast
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    connections:
      - token: ethereum|optimism|0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2
      - token: ethereum|base|0x2552516453368e42705D791F674b312b8b87CD9e
      - token: ethereum|bsc|0xE00C6185a5c19219F1FFeD213b4406a254968c26
      - token: ethereum|mode|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|linea|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|ethereum|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|fraxtal|0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5
      - token: ethereum|taiko|0x4b6aB5F819A515382B0dEB6935D793817bB4af28
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20
    symbol: ezETH
  - addressOrDenom: "0xE00C6185a5c19219F1FFeD213b4406a254968c26"
    chainName: bsc
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    connections:
      - token: ethereum|optimism|0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2
      - token: ethereum|base|0x2552516453368e42705D791F674b312b8b87CD9e
      - token: ethereum|blast|0x486b39378f99f073A3043C6Aabe8666876A8F3C5
      - token: ethereum|mode|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|linea|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|ethereum|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|fraxtal|0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5
      - token: ethereum|taiko|0x4b6aB5F819A515382B0dEB6935D793817bB4af28
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20
    symbol: ezETH
  - addressOrDenom: "0xC59336D8edDa9722B4f1Ec104007191Ec16f7087"
    chainName: mode
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    connections:
      - token: ethereum|optimism|0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2
      - token: ethereum|base|0x2552516453368e42705D791F674b312b8b87CD9e
      - token: ethereum|blast|0x486b39378f99f073A3043C6Aabe8666876A8F3C5
      - token: ethereum|bsc|0xE00C6185a5c19219F1FFeD213b4406a254968c26
      - token: ethereum|linea|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|ethereum|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|fraxtal|0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5
      - token: ethereum|taiko|0x4b6aB5F819A515382B0dEB6935D793817bB4af28
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20
    symbol: ezETH
  - addressOrDenom: "0xC59336D8edDa9722B4f1Ec104007191Ec16f7087"
    chainName: linea
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    connections:
      - token: ethereum|optimism|0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2
      - token: ethereum|base|0x2552516453368e42705D791F674b312b8b87CD9e
      - token: ethereum|blast|0x486b39378f99f073A3043C6Aabe8666876A8F3C5
      - token: ethereum|bsc|0xE00C6185a5c19219F1FFeD213b4406a254968c26
      - token: ethereum|mode|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|ethereum|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|fraxtal|0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5
      - token: ethereum|taiko|0x4b6aB5F819A515382B0dEB6935D793817bB4af28
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20
    symbol: ezETH
  - addressOrDenom: "0xC59336D8edDa9722B4f1Ec104007191Ec16f7087"
    chainName: ethereum
    collateralAddressOrDenom: "0xC8140dA31E6bCa19b287cC35531c2212763C2059"
    connections:
      - token: ethereum|optimism|0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2
      - token: ethereum|base|0x2552516453368e42705D791F674b312b8b87CD9e
      - token: ethereum|blast|0x486b39378f99f073A3043C6Aabe8666876A8F3C5
      - token: ethereum|bsc|0xE00C6185a5c19219F1FFeD213b4406a254968c26
      - token: ethereum|mode|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|linea|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|fraxtal|0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5
      - token: ethereum|taiko|0x4b6aB5F819A515382B0dEB6935D793817bB4af28
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20Lockbox
    symbol: ezETH
  - addressOrDenom: "0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5"
    chainName: fraxtal
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    connections:
      - token: ethereum|optimism|0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2
      - token: ethereum|base|0x2552516453368e42705D791F674b312b8b87CD9e
      - token: ethereum|blast|0x486b39378f99f073A3043C6Aabe8666876A8F3C5
      - token: ethereum|bsc|0xE00C6185a5c19219F1FFeD213b4406a254968c26
      - token: ethereum|mode|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|linea|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|ethereum|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|taiko|0x4b6aB5F819A515382B0dEB6935D793817bB4af28
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20
    symbol: ezETH
  - addressOrDenom: "0x4b6aB5F819A515382B0dEB6935D793817bB4af28"
    chainName: taiko
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    connections:
      - token: ethereum|optimism|0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2
      - token: ethereum|base|0x2552516453368e42705D791F674b312b8b87CD9e
      - token: ethereum|blast|0x486b39378f99f073A3043C6Aabe8666876A8F3C5
      - token: ethereum|bsc|0xE00C6185a5c19219F1FFeD213b4406a254968c26
      - token: ethereum|mode|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|linea|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|ethereum|0xC59336D8edDa9722B4f1Ec104007191Ec16f7087
      - token: ethereum|fraxtal|0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5
    decimals: 18
    logoURI: /deployments/warp_routes/EZETH/logo.svg
    name: Renzo Restaked ETH
    standard: EvmHypXERC20
    symbol: ezETH
options: {}
