# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  ## GSP
  - chainName: pruv
    standard: EvmHypCollateral
    decimals: 6
    symbol: GSP
    name: Garuda Sports Group
    addressOrDenom: '0x92e3582717B09462E4Aa01203a89BB176283C20c'
    collateralAddressOrDenom: '0x8f038c1ee8fcb6c70b1d103a3b9cefd4d6401998'
    connections:
      - token: ethereum|mantapacific|0xFB13Ad8c286025E1874D631bC62EAde352f05d33
  - chainName: mantapacific
    standard: EvmHypSynthetic
    decimals: 6
    symbol: GSP
    name: Garuda Sports Group
    addressOrDenom: '0xFB13Ad8c286025E1874D631bC62EAde352f05d33'
    connections:
      - token: ethereum|pruv|0x92e3582717B09462E4Aa01203a89BB176283C20c
## GSP

options: {}
