# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  # - addressOrDenom: '0xcC2816aC3fe471e5378BBd3B30F2B8247021625D'
  #   chainName: basesepolia
  #   collateralAddressOrDenom: '0x7bD1331A7c4E32F3aD9Ca14Ad0E7FAb0d4F380Ec'
  #   connections:
  #     - token: ethereum|sepolia|0x781bE492F1232E66990d83a9D3AC3Ec26f56DAfB
  #   decimals: 6
  #   name: USDC
  #   standard: EvmHypCollateral
  #   symbol: USDC
  # - addressOrDenom: '0x781bE492F1232E66990d83a9D3AC3Ec26f56DAfB'
  #   chainName: sepolia
  #   connections:
  #     - token: ethereum|basesepolia|0xcC2816aC3fe471e5378BBd3B30F2B8247021625D
  #   decimals: 6
  #   name: USDC
  #   standard: EvmHypSynthetic
  #   symbol: USDC
  # - addressOrDenom: '0x5c12ADC734699C07b095fe30B8312F1A7bbaA788'
  #   chainName: basesepolia
  #   connections:
  #     - token: ethereum|sepolia|0x95878Fd41bC26f7045C0b98e381c22f010745A75
  #   decimals: 18
  #   name: Ether
  #   standard: EvmHypNative
  #   symbol: ETH
  # - addressOrDenom: '0x95878Fd41bC26f7045C0b98e381c22f010745A75'
  #   chainName: sepolia
  #   connections:
  #     - token: ethereum|basesepolia|0x5c12ADC734699C07b095fe30B8312F1A7bbaA788
  #   decimals: 18
  #   name: Ether
  #   standard: EvmHypNative
  #   symbol: ETH
  - addressOrDenom: '0x783EC5e105234a570eB90f314284E5dBe53bdd90'
    chainName: basesepolia
    connections:
      - token: ethereum|sepolia|0x79B1257BDBCaeF98Da685A7c225b6e61a119Cb7a
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: '0x79B1257BDBCaeF98Da685A7c225b6e61a119Cb7a'
    chainName: sepolia
    connections:
      - token: ethereum|basesepolia|0x783EC5e105234a570eB90f314284E5dBe53bdd90
    decimals: 18
    name: Ether
    standard: EvmHypSynthetic
    symbol: ETH

  # 10% of amount
  - addressOrDenom: '0x9534122Aae7978dB8f5f10dF4432233c53e820A1'
    chainName: basesepolia
    collateralAddressOrDenom: '0x7bd1331a7c4e32f3ad9ca14ad0e7fab0d4f380ec'
    connections:
      - token: ethereum|sepolia|0x7b75b29caD47e10146e29BBf7BD9025e021a7023
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: '0x7b75b29caD47e10146e29BBf7BD9025e021a7023'
    chainName: sepolia
    collateralAddressOrDenom: '0x3edf60dd017ace33a0220f78741b5581c385a1ba'
    connections:
      - token: ethereum|basesepolia|0x9534122Aae7978dB8f5f10dF4432233c53e820A1
    decimals: 6
    name: USDZ
    standard: EvmHypCollateral
    symbol: USDZ

  # 5% of amount
  - addressOrDenom: '0xfF26696DcDb6BbFD27e959b847D4f1399D5BcF64'
    chainName: basesepolia
    collateralAddressOrDenom: '0x7bd1331a7c4e32f3ad9ca14ad0e7fab0d4f380ec'
    connections:
      - token: ethereum|sepolia|0xe03dad16074BC5EEA9A9311257BF02Eb0B6AAA2b
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: '0xe03dad16074BC5EEA9A9311257BF02Eb0B6AAA2b'
    chainName: sepolia
    collateralAddressOrDenom: '0x3edf60dd017ace33a0220f78741b5581c385a1ba'
    connections:
      - token: ethereum|basesepolia|0xfF26696DcDb6BbFD27e959b847D4f1399D5BcF64
    decimals: 6
    name: USDZ
    standard: EvmHypCollateral
    symbol: USDZ

  # no fee
  - addressOrDenom: '0xD35Aa652C1F808d3f87DA3DC7974fea888D7d625'
    chainName: basesepolia
    collateralAddressOrDenom: '0x7bd1331a7c4e32f3ad9ca14ad0e7fab0d4f380ec'
    connections:
      - token: ethereum|sepolia|0x4Eb82Ee35b0a1c1d776E3a3B547f9A9bA6FCC9f2
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: '0x4Eb82Ee35b0a1c1d776E3a3B547f9A9bA6FCC9f2'
    chainName: sepolia
    collateralAddressOrDenom: '0x3edf60dd017ace33a0220f78741b5581c385a1ba'
    connections:
      - token: ethereum|basesepolia|0xD35Aa652C1F808d3f87DA3DC7974fea888D7d625
    decimals: 6
    name: USDZ
    standard: EvmHypCollateral
    symbol: USDZ
options: {}
