# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: arbitrum
    standard: EvmHypXERC20
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0x1217441e6E8E960D065698317FE13594a5704f69'
    connections:
      - token: ethereum|optimism|0xEF90AF9FCC831c5E2266285C4A1787201f96736a
      - token: ethereum|base|0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf
      - token: ethereum|blast|0xB951c9b16603825C285bf59b14e983047d421Af5
      - token: ethereum|bsc|0x9Ff085A556A498395B9edA690666E3BD34751024
      - token: ethereum|mode|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|linea|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|ethereum|0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1
      - token: ethereum|fraxtal|0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B
  - chainName: optimism
    standard: EvmHypXERC20
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0xEF90AF9FCC831c5E2266285C4A1787201f96736a'
    connections:
      - token: ethereum|arbitrum|0x1217441e6E8E960D065698317FE13594a5704f69
      - token: ethereum|base|0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf
      - token: ethereum|blast|0xB951c9b16603825C285bf59b14e983047d421Af5
      - token: ethereum|bsc|0x9Ff085A556A498395B9edA690666E3BD34751024
      - token: ethereum|mode|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|linea|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|ethereum|0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1
      - token: ethereum|fraxtal|0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B
  - chainName: base
    standard: EvmHypXERC20
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf'
    connections:
      - token: ethereum|arbitrum|0x1217441e6E8E960D065698317FE13594a5704f69
      - token: ethereum|optimism|0xEF90AF9FCC831c5E2266285C4A1787201f96736a
      - token: ethereum|blast|0xB951c9b16603825C285bf59b14e983047d421Af5
      - token: ethereum|bsc|0x9Ff085A556A498395B9edA690666E3BD34751024
      - token: ethereum|mode|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|linea|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|ethereum|0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1
      - token: ethereum|fraxtal|0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B
  - chainName: blast
    standard: EvmHypXERC20
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0xB951c9b16603825C285bf59b14e983047d421Af5'
    connections:
      - token: ethereum|arbitrum|0x1217441e6E8E960D065698317FE13594a5704f69
      - token: ethereum|optimism|0xEF90AF9FCC831c5E2266285C4A1787201f96736a
      - token: ethereum|base|0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf
      - token: ethereum|bsc|0x9Ff085A556A498395B9edA690666E3BD34751024
      - token: ethereum|mode|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|linea|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|ethereum|0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1
      - token: ethereum|fraxtal|0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B
  - chainName: bsc
    standard: EvmHypXERC20
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0x9Ff085A556A498395B9edA690666E3BD34751024'
    connections:
      - token: ethereum|arbitrum|0x1217441e6E8E960D065698317FE13594a5704f69
      - token: ethereum|optimism|0xEF90AF9FCC831c5E2266285C4A1787201f96736a
      - token: ethereum|base|0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf
      - token: ethereum|blast|0xB951c9b16603825C285bf59b14e983047d421Af5
      - token: ethereum|mode|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|linea|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|ethereum|0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1
      - token: ethereum|fraxtal|0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B
  - chainName: mode
    standard: EvmHypXERC20
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0x477614191C3ccF8e10a6D1291dBAf098D17497BE'
    connections:
      - token: ethereum|arbitrum|0x1217441e6E8E960D065698317FE13594a5704f69
      - token: ethereum|optimism|0xEF90AF9FCC831c5E2266285C4A1787201f96736a
      - token: ethereum|base|0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf
      - token: ethereum|blast|0xB951c9b16603825C285bf59b14e983047d421Af5
      - token: ethereum|bsc|0x9Ff085A556A498395B9edA690666E3BD34751024
      - token: ethereum|linea|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|ethereum|0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1
      - token: ethereum|fraxtal|0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B
  - chainName: linea
    standard: EvmHypXERC20
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0x477614191C3ccF8e10a6D1291dBAf098D17497BE'
    connections:
      - token: ethereum|arbitrum|0x1217441e6E8E960D065698317FE13594a5704f69
      - token: ethereum|optimism|0xEF90AF9FCC831c5E2266285C4A1787201f96736a
      - token: ethereum|base|0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf
      - token: ethereum|blast|0xB951c9b16603825C285bf59b14e983047d421Af5
      - token: ethereum|bsc|0x9Ff085A556A498395B9edA690666E3BD34751024
      - token: ethereum|mode|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|ethereum|0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1
      - token: ethereum|fraxtal|0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B
  - chainName: ethereum
    standard: EvmHypXERC20Lockbox
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1'
    connections:
      - token: ethereum|arbitrum|0x1217441e6E8E960D065698317FE13594a5704f69
      - token: ethereum|optimism|0xEF90AF9FCC831c5E2266285C4A1787201f96736a
      - token: ethereum|base|0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf
      - token: ethereum|blast|0xB951c9b16603825C285bf59b14e983047d421Af5
      - token: ethereum|bsc|0x9Ff085A556A498395B9edA690666E3BD34751024
      - token: ethereum|mode|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|linea|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|fraxtal|0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B
  - chainName: fraxtal
    standard: EvmHypXERC20
    decimals: 18
    symbol: ezETH
    logoURI: https://renzo.hyperlane.xyz/logos/ezeth.svg
    name: Renzo Restaked ETH
    addressOrDenom: '0xdFf621F952c23972dFD3A9E5d7B9f6339e9c078B'
    connections:
      - token: ethereum|arbitrum|0x1217441e6E8E960D065698317FE13594a5704f69
      - token: ethereum|optimism|0xEF90AF9FCC831c5E2266285C4A1787201f96736a
      - token: ethereum|base|0x4b36617B3D2cAb714a056090306A88Dd6DD4cCcf
      - token: ethereum|blast|0xB951c9b16603825C285bf59b14e983047d421Af5
      - token: ethereum|bsc|0x9Ff085A556A498395B9edA690666E3BD34751024
      - token: ethereum|mode|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|linea|0x477614191C3ccF8e10a6D1291dBAf098D17497BE
      - token: ethereum|ethereum|0x0B386cAe2851E954b52D10Aee4ba8CCDC11463E1
