tokens:
  # Arbitrum USDC
  - chainName: arbitrum
    standard: EvmHypStableSwap
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: '0x94C62e7958738B65737a0Db8A5077def3AED84AA'
    collateralAddressOrDenom: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831'
    logoURI: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/deployments/warp_routes/USDC/logo.svg
    stableSwapPool: mainnet-stableswap-pool
    helperAddress: '0x56db6AF01e03E31695F847633F0F15eF857D4179'
    sUSDAddress: '0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6'
    adapterAddress: '0x94C62e7958738B65737a0Db8A5077def3AED84AA'
    connections:
      - token: ethereum|arbitrum|0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af
      - token: ethereum|base|0x73Ef899fDa87213e26501707ab585028BFB297c8
      - token: ethereum|base|0x23c51024b19303F1315DbFFA055666aE9B7A0B2c
      - token: ethereum|soneium|0x867D428B8FbE196EA4e997e7980623E75ED219a7
      - token: ethereum|hyperevm|0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575
      - token: ethereum|linea|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895
      - token: ethereum|mantra|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895

  # Arbitrum USDT
  - chainName: arbitrum
    standard: EvmHypStableSwap
    decimals: 6
    symbol: USDT
    name: Tether USD
    addressOrDenom: '0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af'
    collateralAddressOrDenom: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9'
    logoURI: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/deployments/warp_routes/USDT/logo.svg
    stableSwapPool: mainnet-stableswap-pool
    helperAddress: '0x56db6AF01e03E31695F847633F0F15eF857D4179'
    sUSDAddress: '0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6'
    adapterAddress: '0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af'
    connections:
      - token: ethereum|arbitrum|0x94C62e7958738B65737a0Db8A5077def3AED84AA
      - token: ethereum|base|0x73Ef899fDa87213e26501707ab585028BFB297c8
      - token: ethereum|base|0x23c51024b19303F1315DbFFA055666aE9B7A0B2c
      - token: ethereum|soneium|0x867D428B8FbE196EA4e997e7980623E75ED219a7
      - token: ethereum|hyperevm|0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575
      - token: ethereum|linea|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895
      - token: ethereum|mantra|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895

  # Base USDC
  - chainName: base
    standard: EvmHypStableSwap
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: '0x73Ef899fDa87213e26501707ab585028BFB297c8'
    collateralAddressOrDenom: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'
    logoURI: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/deployments/warp_routes/USDC/logo.svg
    stableSwapPool: mainnet-stableswap-pool
    helperAddress: '0x9650deA331801F944335669a8569ed39f7AEf342'
    sUSDAddress: '0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6'
    adapterAddress: '0x73Ef899fDa87213e26501707ab585028BFB297c8'
    connections:
      - token: ethereum|base|0x23c51024b19303F1315DbFFA055666aE9B7A0B2c
      - token: ethereum|arbitrum|0x94C62e7958738B65737a0Db8A5077def3AED84AA
      - token: ethereum|arbitrum|0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af
      - token: ethereum|soneium|0x867D428B8FbE196EA4e997e7980623E75ED219a7
      - token: ethereum|hyperevm|0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575
      - token: ethereum|linea|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895
      - token: ethereum|mantra|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895

  # Base USDT
  - chainName: base
    standard: EvmHypStableSwap
    decimals: 6
    symbol: USDT
    name: Tether USD
    addressOrDenom: '0x23c51024b19303F1315DbFFA055666aE9B7A0B2c'
    collateralAddressOrDenom: '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2'
    logoURI: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/deployments/warp_routes/USDT/logo.svg
    stableSwapPool: mainnet-stableswap-pool
    helperAddress: '0x9650deA331801F944335669a8569ed39f7AEf342'
    sUSDAddress: '0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6'
    adapterAddress: '0x23c51024b19303F1315DbFFA055666aE9B7A0B2c'
    connections:
      - token: ethereum|base|0x73Ef899fDa87213e26501707ab585028BFB297c8
      - token: ethereum|arbitrum|0x94C62e7958738B65737a0Db8A5077def3AED84AA
      - token: ethereum|arbitrum|0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af
      - token: ethereum|soneium|0x867D428B8FbE196EA4e997e7980623E75ED219a7
      - token: ethereum|hyperevm|0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575
      - token: ethereum|linea|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895
      - token: ethereum|mantra|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895

  # Soneium Startale USD (USDSC)
  - chainName: soneium
    standard: EvmHypStableSwap
    decimals: 6
    symbol: USDSC
    name: Startale USD
    addressOrDenom: '0x867D428B8FbE196EA4e997e7980623E75ED219a7'
    collateralAddressOrDenom: '0x3f99231dD03a9F0E7e3421c92B7b90fbe012985a'
    logoURI: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/deployments/warp_routes/USDSC/logo.svg
    stableSwapPool: mainnet-stableswap-pool
    helperAddress: '0xcA45246445A047670B67F87c5AC75A4DbE5134F1'
    sUSDAddress: '0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6'
    adapterAddress: '0x867D428B8FbE196EA4e997e7980623E75ED219a7'
    connections:
      - token: ethereum|arbitrum|0x94C62e7958738B65737a0Db8A5077def3AED84AA
      - token: ethereum|arbitrum|0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af
      - token: ethereum|base|0x73Ef899fDa87213e26501707ab585028BFB297c8
      - token: ethereum|base|0x23c51024b19303F1315DbFFA055666aE9B7A0B2c
      - token: ethereum|hyperevm|0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575
      - token: ethereum|linea|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895
      - token: ethereum|mantra|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895

  # HyperEVM USDH
  - chainName: hyperevm
    standard: EvmHypStableSwap
    decimals: 6
    symbol: USDH
    name: USD Hyperliquid
    addressOrDenom: '0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575'
    collateralAddressOrDenom: '0x111111a1a0667d36bd57c0a9f569b98057111111'
    stableSwapPool: mainnet-stableswap-pool
    helperAddress: '0x7e97865321a4a16B7DDc4ea5387E63ED1999b6d7'
    sUSDAddress: '0x0a089A151228Fd8CdfB1082a12b030D4C064F497'
    adapterAddress: '0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575'
    connections:
      - token: ethereum|arbitrum|0x94C62e7958738B65737a0Db8A5077def3AED84AA
      - token: ethereum|arbitrum|0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af
      - token: ethereum|base|0x73Ef899fDa87213e26501707ab585028BFB297c8
      - token: ethereum|base|0x23c51024b19303F1315DbFFA055666aE9B7A0B2c
      - token: ethereum|soneium|0x867D428B8FbE196EA4e997e7980623E75ED219a7
      - token: ethereum|linea|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895
      - token: ethereum|mantra|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895

  # Linea mUSD
  - chainName: linea
    standard: EvmHypStableSwap
    decimals: 6
    symbol: mUSD
    name: MetaMask USD
    addressOrDenom: '0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895'
    collateralAddressOrDenom: '0xaca92e438df0b2401ff60da7e4337b687a2435da'
    stableSwapPool: mainnet-stableswap-pool
    helperAddress: '0x3856c8A14cf1D1da69237B8e79aDb4E3eE44fba2'
    sUSDAddress: '0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6'
    adapterAddress: '0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895'
    connections:
      - token: ethereum|arbitrum|0x94C62e7958738B65737a0Db8A5077def3AED84AA
      - token: ethereum|arbitrum|0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af
      - token: ethereum|base|0x73Ef899fDa87213e26501707ab585028BFB297c8
      - token: ethereum|base|0x23c51024b19303F1315DbFFA055666aE9B7A0B2c
      - token: ethereum|soneium|0x867D428B8FbE196EA4e997e7980623E75ED219a7
      - token: ethereum|hyperevm|0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575
      - token: ethereum|mantra|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895

  # MANTRA mantraUSD
  - chainName: mantra
    standard: EvmHypStableSwap
    decimals: 6
    symbol: mantraUSD
    name: MANTRA USD
    addressOrDenom: '0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895'
    collateralAddressOrDenom: '0xd2b95283011E47257917770D28Bb3EE44c849f6F'
    stableSwapPool: mainnet-stableswap-pool
    helperAddress: '0xF0d9D232141dF68DD3CE272dd216C8D71645F25A'
    sUSDAddress: '0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6'
    adapterAddress: '0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895'
    connections:
      - token: ethereum|arbitrum|0x94C62e7958738B65737a0Db8A5077def3AED84AA
      - token: ethereum|arbitrum|0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af
      - token: ethereum|base|0x73Ef899fDa87213e26501707ab585028BFB297c8
      - token: ethereum|base|0x23c51024b19303F1315DbFFA055666aE9B7A0B2c
      - token: ethereum|soneium|0x867D428B8FbE196EA4e997e7980623E75ED219a7
      - token: ethereum|hyperevm|0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575
      - token: ethereum|linea|0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895
